source: build/bundled
url: http://shop.bluetree.jp

# Site settings
title: shop.bluetree.jp
year: 2016
email: aokinobu@gmail.dot.com
description: "bluetree.jp is where you can find everything about the bluetree family."
permalink: date

paginate: 4
paginate_path: /blog/page:num/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 005CE6
  #primary: 4242ef
  #secondary: 2E2EA7
  secondary: 004AB8
  secondary-dark: FFF

# Team names, titles and social links
people:
- name: Nobuyuki Aoki
  pic: 1
  position: Blue Tree Creator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aokinobu
  - title: facebook
    url: http://facebook.com/aokinobu
  - title: rss
    url: /rss.xml
  - title: bitbucket 
    url: http://bitbucket.org/aokinobu
  - title: github
    url: http://github.com/aokinobu

# Postal address (add as many lines as necessary)
address:
  - line: 1234 Blue Tree Lane
  - line: Ibaragi, Japan

# Build settings
markdown: kramdown

gems: 
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
